version: '3'

networks:
  default:
    name: portfolio
    driver: bridge

  kua-internal:
    name: kua-internal
    external: true

services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - kua-internal
      - default
    env_file:
      - .env
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - NOCO_EMAIL=${NOCO_EMAIL}
      - NOCO_PASS=${NOCO_PASS}
      - API_URL=${API_URL}
      - API_ENDPOINT_LINKS=${API_ENDPOINT_LINKS}
      - API_ENDPOINT_BRANDS=${API_ENDPOINT_BRANDS}
      - API_ENDPOINT_ENTRIES=${API_ENDPOINT_ENTRIES}
      - API_ENDPOINT_CATEGORIES=${API_ENDPOINT_CATEGORIES}
      - API_ENDPOINT_BADGES=${API_ENDPOINT_BADGES}
      - API_ENDPOINT_ENTRY_TYPES=${API_ENDPOINT_ENTRY_TYPES}
      - ENTRIES_TO_BADGES_RECORD=${ENTRIES_TO_BADGES_RECORD}

  cloudflared:
    image: cloudflare/cloudflared
    restart: always
    networks:
      - default
      - kua-internal
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
